version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
  web:
    build: .
    #entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db

